version: "2.12"
services:
  modem:
    image: modem
    container_name: "modem"
    #network_mode: "host"
    volumes:
      - /var/run/dbus:/var/run/dbus 
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket 
      - /home/ors/Downloads:/var/data 
    devices: 
      - "/dev/net/tun:/dev/net/tun"
      - "/var/run/smcroute.sock:/var/run/smcroute.sock"
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    ports:
      - "3010"
      - "3020"
      - "5520"
    networks:
      public-net:
        ipv4_address: 192.168.5.2
      
  middleware:
    image: mbms-middleware
    container_name: "mw"
    #network_mode: "host"
    privileged: true
    ports:
      - "3010"
      - "2947"
    networks:
      public-net:
        ipv4_address: 192.168.5.3   

  wui:
    image: wui
    container_name: "wui"
    #network_mode: "host"
    privileged: true
    ports:
      - "3000:3000"
      - "3020"
      - "3010"
    networks:
      public-net:
        ipv4_address: 192.168.5.4


  nginx:
    image: nginxm
    container_name: "nginx"
    #network_mode: "host"
    privileged: true
    ports:
      - "80:80"
    networks:
      public-net:
        ipv4_address: 192.168.5.5

networks:
  public-net:
    name: obeca-net
    ipam:
      config:
        - subnet: 192.168.5.1/24

